import { RouteInfo } from './sidebar.metadata';
import {Role} from "../../core/models/security/role";
export const ROUTES: RouteInfo[] = [
    {
        path: '',
        title: 'training.organisation.text',
        moduleName: 'organisation',
        iconType: 'material-icons-two-tone',
        icon: 'auto_graph',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        roles: [Role.SUPER, Role.ADMIN, Role.ORGANISER],
        submenu: [
            {
                path: '/organisation/training/broadcast',
                title: 'training.organisation.broadcast',
                moduleName: 'organisation',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN, Role.ORGANISER],
                submenu: []
            },
            // {
            //     path: '/organisation/planning',
            //     title: 'training.organisation.planning',
            //     moduleName: 'organisation',
            //     iconType: '',
            //     icon: '',
            //     class: 'ml-menu',
            //     groupTitle: false,
            //     badge: '',
            //     badgeClass: '',
            //     roles: [Role.SUPER, Role.ADMIN, Role.ORGANISER],
            //     submenu: []
            // },
            // {
            //     path: '/organisation/calendar',
            //     title: 'training.organisation.calendar',
            //     moduleName: 'organisation',
            //     iconType: '',
            //     icon: '',
            //     class: 'ml-menu',
            //     groupTitle: false,
            //     badge: '',
            //     badgeClass: '',
            //     roles: [Role.SUPER, Role.ADMIN, Role.ORGANISER],
            //     submenu: []
            // },
            {
                path: '/organisation/training/page',
                title: 'training.page',
                moduleName: 'organisation',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN, Role.ORGANISER],
                submenu: []
            },
            // {
            //     path: '/organisation/dashboard',
            //     title: 'training.organisation.dashboard',
            //     moduleName: 'organisation',
            //     iconType: '',
            //     icon: '',
            //     class: 'ml-menu',
            //     groupTitle: false,
            //     badge: '',
            //     badgeClass: '',
            //     roles: [Role.SUPER, Role.ADMIN, Role.ORGANISER],
            //     submenu: []
            // }
        ],
    },
    {
        path: '',
        title: 'training.partnership.text',
        moduleName: 'partnership',
        iconType: 'material-icons-two-tone',
        icon: 'group_work',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        roles: [Role.SUPER, Role.PARTNER],
        submenu: [
            {
                path: '/partnership/participants',
                title: 'training.partnership.participants',
                moduleName: 'partnership',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN, Role.PARTNER],
                submenu: [],
            },
            // {
            //     path: '/partnership/request',
            //     title: 'training.partnership.request',
            //     moduleName: 'partnership',
            //     iconType: '',
            //     icon: '',
            //     class: 'ml-menu',
            //     groupTitle: false,
            //     badge: '',
            //     badgeClass: '',
            //     roles: [Role.SUPER, Role.ADMIN, Role.PARTNER],
            //     submenu: [],
            // },
            // {
            //     path: '/partnership/demands',
            //     title: 'training.partnership.demands',
            //     moduleName: 'partnership',
            //     iconType: '',
            //     icon: '',
            //     class: 'ml-menu',
            //     groupTitle: false,
            //     badge: '',
            //     badgeClass: '',
            //     roles: [Role.SUPER, Role.ADMIN, Role.PARTNER],
            //     submenu: [],
            // },
            // {
            //     path: '/partnership/dashboard',
            //     title: 'training.partnership.dashboard',
            //     moduleName: 'partnership',
            //     iconType: '',
            //     icon: '',
            //     class: 'ml-menu',
            //     groupTitle: false,
            //     badge: '',
            //     badgeClass: '',
            //     roles: [Role.SUPER, Role.ADMIN, Role.PARTNER],
            //     submenu: [],
            // }
        ],
    },

    {
        path: '',
        title: 'training.attendee.text',
        moduleName: 'attendee',
        iconType: 'material-icons-two-tone',
        icon: 'perm_media',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        roles: [Role.SUPER, Role.ADMIN, Role.ATTENDEE],
        submenu: [
            {
                path: '/attendee/charts',
                title: 'training.attendee.charts',
                moduleName: 'attendee',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN, Role.PARTNER],
                submenu: [],
            },
        ],
    },

    {
        path: '',
        title: 'training.configuration.text',
        moduleName: 'configuration',
        iconType: 'material-icons-two-tone',
        icon: 'settings_suggest',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        roles: [Role.SUPER, Role.ADMIN],
        submenu: [
            {
                path: '/configuration/topic/page',
                title: 'training.configuration.list.topic',
                moduleName: 'configuration',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN],
                submenu: [],
            },
            {
                path: '/configuration/institution/page',
                title: 'training.configuration.list.facility',
                moduleName: 'configuration',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN],
                submenu: [],
            },
            {
                path: '/configuration/account/page',
                title: 'training.configuration.list.account',
                moduleName: 'configuration',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN],
                submenu: [],
            },
            {
                path: '/configuration/category/page',
                title: 'training.configuration.list.category',
                moduleName: 'configuration',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                roles: [Role.SUPER, Role.ADMIN],
                submenu: [],
            }
        ],
    },
];
