package org.charess.training.domain.security;

public enum Status {

    USER_ACTIVE,
    USER_LOCKED,
    USER_PENDING,
    USER_INACTIVE,

    TRAINING_BROADCAST,

    TRAINING_REQUESTED, //
    TRAINING_VALIDATED,
    TRAINING_REJECTED,
    TRAINING_PENDING,
    TRAINING_COMPLETED,
    TRAINING_UNCOMPLETED,

    MODE_ON_SITE,
    MODE_ON_LINE,
    TEST_TYPE_AUTO,
    TEST_TYPE_PRE_AND_POST,


    PARTICPANT_DECLARED,
    PARTICPANT_CONFIRMED,
    PARTICPANT_PARTICIPATED,
    PARTICPANT_FAILED,
    PARTICPANT_SUCCEEDED,
    PARTICPANT_ABANDONED

}
