package org.charess.training.domain.security;

public enum Status {

    USER_ACTIVE,
    USER_LOCKED,
    USER_PENDING,
    USER_INACTIVE,

    TRAINING_REQUESTED,
    TRAINING_VALIDATED,
    TRAINING_REJECTED,
    TRAINING_PENDING,
    TRAINING_COMPLETED,
    TRAINING_UNCOMPLETED
}
